[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "turbolaunch"
version = "1.0.0"
description = "The definitive command-line arguments parser"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
keywords = ["cli", "argparse", "library"]
classifiers = [
  "Development Status :: 3 - Alpha",

  # Indicate who your project is intended for
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",

  # Specify the Python versions you support here. In particular, ensure
  # that you indicate you support Python 3. These classifiers are *not*
  # checked by "pip install". See instead "requires-python" key in this file.
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3 :: Only",
]

[[project.authors]]
name = "Sam Vervaeck"
email = "samvv@pm.me"

[[project.maintainers]]
name = "Sam Vervaeck"
email = "samvv@pm.me"

[project.optional-dependencies]
dev = ["check-manifest"]
test = ["coverage"]

[project.urls]
"Homepage" = "https://github.com/samvv/turbolaunch"
"Bug Reports" = "https://github.com/samvv/turbolaunch/issues"
"Source" = "https://github.com/samvv/turbolaunch/"

[tool.setuptools]
# If there are data files included in your packages that need to be
# installed, specify them here.
#package-data = { "sample" = ["*.dat"] }
